# Generated by Django 4.1.7 on 2023-12-22 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("furniture", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Планировка", "verbose_name_plural": "Планировки"},
        ),
    ]
