# Generated by Django 4.1.7 on 2023-05-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='furniture/', verbose_name='Изображение мебели'),
        ),
    ]
