# Generated by Django 4.1.7 on 2023-04-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='furniture',
            new_name='furniture_placement',
        ),
    ]
