# Generated by Django 4.1.7 on 2023-06-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(verbose_name='X')),
                ('y', models.PositiveIntegerField(verbose_name='Y')),
            ],
        ),
        migrations.RemoveField(
            model_name='door',
            name='ne_coordinate',
        ),
        migrations.RemoveField(
            model_name='door',
            name='nw_coordinate',
        ),
        migrations.RemoveField(
            model_name='door',
            name='se_coordinate',
        ),
        migrations.RemoveField(
            model_name='door',
            name='sw_coordinate',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='ne_coordinate',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='nw_coordinate',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='se_coordinate',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='sw_coordinate',
        ),
        migrations.RemoveField(
            model_name='powersocket',
            name='ne_coordinate',
        ),
        migrations.RemoveField(
            model_name='powersocket',
            name='nw_coordinate',
        ),
        migrations.RemoveField(
            model_name='powersocket',
            name='se_coordinate',
        ),
        migrations.RemoveField(
            model_name='powersocket',
            name='sw_coordinate',
        ),
        migrations.RemoveField(
            model_name='window',
            name='ne_coordinate',
        ),
        migrations.RemoveField(
            model_name='window',
            name='nw_coordinate',
        ),
        migrations.RemoveField(
            model_name='window',
            name='se_coordinate',
        ),
        migrations.RemoveField(
            model_name='window',
            name='sw_coordinate',
        ),
        migrations.AddField(
            model_name='door',
            name='north_east',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='furniture.coordinate', verbose_name='Координата north-east'),
        ),
        migrations.AddField(
            model_name='door',
            name='north_west',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.coordinate', verbose_name='Координата north-west'),
        ),
        migrations.AddField(
            model_name='door',
            name='south_west',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='furniture.coordinate', verbose_name='Координата south-west'),
        ),
        migrations.AddField(
            model_name='placement',
            name='north_east',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='furniture.coordinate', verbose_name='Координата north-east'),
        ),
        migrations.AddField(
            model_name='placement',
            name='north_west',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.coordinate', verbose_name='Координата north-west'),
        ),
        migrations.AddField(
            model_name='placement',
            name='south_west',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='furniture.coordinate', verbose_name='Координата south-west'),
        ),
        migrations.AddField(
            model_name='powersocket',
            name='north_east',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='furniture.coordinate', verbose_name='Координата north-east'),
        ),
        migrations.AddField(
            model_name='powersocket',
            name='north_west',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.coordinate', verbose_name='Координата north-west'),
        ),
        migrations.AddField(
            model_name='powersocket',
            name='south_west',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='furniture.coordinate', verbose_name='Координата south-west'),
        ),
        migrations.AddField(
            model_name='window',
            name='north_east',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='furniture.coordinate', verbose_name='Координата north-east'),
        ),
        migrations.AddField(
            model_name='window',
            name='north_west',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.coordinate', verbose_name='Координата north-west'),
        ),
        migrations.AddField(
            model_name='window',
            name='south_west',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='furniture.coordinate', verbose_name='Координата south-west'),
        ),
    ]
