# Generated by Django 3.2.19 on 2023-06-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Наименование комнаты')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='furniture',
            name='type_of_rooms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to='furniture.typeofroom', verbose_name='Комната'),
            preserve_default=False,
        ),
    ]
