# Generated by Django 4.1.7 on 2023-05-01 19:53

from django.db import migrations, models
import furniture.models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_rename_furniture_room_furniture_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='length_access',
            field=models.PositiveIntegerField(default=0, help_text='Длина c зоной подхода в мм', validators=[furniture.models.minimum_len_width_validator], verbose_name='Длина мебели c зоной подхода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='width_access',
            field=models.PositiveIntegerField(default=2, help_text='Ширина c зоной подхода в мм', validators=[furniture.models.minimum_len_width_validator], verbose_name='Ширина мебели c зоной подхода'),
            preserve_default=False,
        ),
    ]
