# Generated by Django 4.1.7 on 2023-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_alter_furniture_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='door',
            options={'verbose_name': 'Дверь в помещении', 'verbose_name_plural': 'Двери в помещении'},
        ),
        migrations.AlterModelOptions(
            name='placement',
            options={'verbose_name': 'Размещение мебели в помещении', 'verbose_name_plural': 'Размещение мебели в помещении'},
        ),
        migrations.AlterModelOptions(
            name='powersocket',
            options={'verbose_name': 'Розетка в помещении', 'verbose_name_plural': 'Розетки в помещении'},
        ),
        migrations.AlterModelOptions(
            name='window',
            options={'verbose_name': 'Окно в помещении', 'verbose_name_plural': 'Окна в помещении'},
        ),
        migrations.AlterField(
            model_name='door',
            name='open_inside',
            field=models.BooleanField(help_text='Открытие в помещении - 1, из помещения - 0', verbose_name='Направление открытия двери внутрь помещения'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название помещения'),
        ),
    ]
