# Generated by Django 4.1.7 on 2023-05-04 19:55

from django.db import migrations, models
import django.db.models.deletion
import furniture.models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_furniture_length_access_furniture_width_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(help_text='Высота в мм', validators=[furniture.models.minimum_len_width_validator], verbose_name='Высота окна')),
                ('width', models.PositiveIntegerField(help_text='Ширина в мм', validators=[furniture.models.minimum_len_width_validator], verbose_name='Ширина окна')),
                ('x_coordinate', models.FloatField(default=0, verbose_name='Координата окна X')),
                ('y_coordinate', models.FloatField(default=0, verbose_name='Координата окна Y')),
                ('room', models.ForeignKey(help_text='Комната, где размещено окно', on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='furniture.room', verbose_name='Комната')),
            ],
        ),
        migrations.CreateModel(
            name='PowerSocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.FloatField(default=0, verbose_name='Координата розетки X')),
                ('y_coordinate', models.FloatField(default=0, verbose_name='Координата розетки Y')),
                ('room', models.ForeignKey(help_text='Комната, где размещена розетка', on_delete=django.db.models.deletion.CASCADE, related_name='power_sockets', to='furniture.room', verbose_name='Комната')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(help_text='Ширина в мм', validators=[furniture.models.minimum_len_width_validator], verbose_name='Ширина двери')),
                ('x_coordinate', models.FloatField(default=0, verbose_name='Координата двери X')),
                ('y_coordinate', models.FloatField(default=0, verbose_name='Координата двери Y')),
                ('room', models.ForeignKey(help_text='Комната, где размещена дверь', on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='furniture.room', verbose_name='Комната')),
            ],
        ),
    ]
