# Generated by Django 4.1.7 on 2023-06-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_coordinate_remove_door_ne_coordinate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='south_east',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='furniture.coordinate', verbose_name='Координата south-east'),
        ),
        migrations.AddField(
            model_name='placement',
            name='south_east',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='furniture.coordinate', verbose_name='Координата south-east'),
        ),
        migrations.AddField(
            model_name='powersocket',
            name='south_east',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='furniture.coordinate', verbose_name='Координата south-east'),
        ),
        migrations.AddField(
            model_name='window',
            name='south_east',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='furniture.coordinate', verbose_name='Координата south-east'),
        ),
    ]
