# Generated by Django 4.1.7 on 2023-05-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_alter_door_options_alter_placement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения'},
        ),
    ]
