# Generated by Django 4.1.7 on 2023-05-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_window_powersocket_door'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='open_inside',
            field=models.BooleanField(default=0, help_text='Открытие в комнату - 1, из комнаты - 0', verbose_name='Направление открытия двери'),
            preserve_default=False,
        ),
    ]
