# Generated by Django 4.1.7 on 2023-05-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0005_door_open_inside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='x_coordinate',
            field=models.PositiveIntegerField(default=0, verbose_name='Координата двери X'),
        ),
        migrations.AlterField(
            model_name='door',
            name='y_coordinate',
            field=models.PositiveIntegerField(default=0, verbose_name='Координата двери Y'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='x_coordinate',
            field=models.PositiveIntegerField(default=0, verbose_name='Координата мебели X'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='y_coordinate',
            field=models.PositiveIntegerField(default=0, verbose_name='Координата мебели Y'),
        ),
        migrations.AlterField(
            model_name='powersocket',
            name='x_coordinate',
            field=models.PositiveIntegerField(default=0, verbose_name='Координата розетки X'),
        ),
        migrations.AlterField(
            model_name='powersocket',
            name='y_coordinate',
            field=models.PositiveIntegerField(default=0, verbose_name='Координата розетки Y'),
        ),
        migrations.AlterField(
            model_name='window',
            name='x_coordinate',
            field=models.PositiveIntegerField(default=0, verbose_name='Координата окна X'),
        ),
        migrations.AlterField(
            model_name='window',
            name='y_coordinate',
            field=models.PositiveIntegerField(default=0, verbose_name='Координата окна Y'),
        ),
    ]
