# Generated by Django 4.1.7 on 2023-04-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lenght', models.IntegerField(verbose_name='lenght furniture')),
                ('width', models.IntegerField(verbose_name='width furniture')),
                ('x_coordinate', models.FloatField(default=0)),
                ('y_coordinate', models.FloatField(default=0)),
            ],
        ),
    ]
