# Generated by Django 5.0.7 on 2025-07-10 18:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Проект', max_length=64, verbose_name='Название проекта')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('layout_requests_left', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0, message='Количество запросов на макет не может быть меньше 0'), django.core.validators.MaxValueValidator(4, message='Количество запросов на макет не может быть больше 4')], verbose_name='Количество запросов на макет')),
                ('preferred_layout_id', models.IntegerField(null=True, verbose_name='Предпочитаемый макет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
