# Generated by Django 3.2.19 on 2023-06-23 10:52

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Наименование тарифа')),
                ('name_english', models.CharField(max_length=256, unique=True, verbose_name='Наименование тарифа на английском языке')),
                ('description', models.TextField(verbose_name='Описание тарифа')),
                ('cost', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Тариф должен быть больше 0 руб в мес')], verbose_name='Стоимость')),
                ('period', models.DurationField(default=datetime.timedelta(days=30), verbose_name='Период действия тарифа')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='UsersTariffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала периода')),
                ('stop_date', models.DateTimeField(verbose_name='Дата окончания периода')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.tariff', verbose_name='Тариф Пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь: Тариф',
                'verbose_name_plural': 'Пользователи: Тарифы',
            },
        ),
    ]
