# Generated by Django 4.1.7 on 2023-12-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="project_limit",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество планировок"
            ),
        ),
        migrations.AddField(
            model_name="tariff",
            name="rooms_limit",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество комнат"
            ),
        ),
    ]
