# Generated by Django 3.2.19 on 2023-06-23 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstariffs',
            name='stop_date',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.DurationField(default=datetime.timedelta(days=30), help_text='Дни, часы, минуты', verbose_name='Период действия тарифа'),
        ),
    ]
