# Generated by Django 4.1.7 on 2023-12-26 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0002_tariff_project_limit_tariff_rooms_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tariff",
            name="actions",
        ),
    ]
