# Generated by Django 4.1.7 on 2024-03-04 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstariffs',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_tariff', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='possibleactionstariff',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_tariff', to='tariff.possibleactions', verbose_name='Действия'),
        ),
        migrations.AddField(
            model_name='possibleactionstariff',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_tariff', to='tariff.tariff'),
        ),
        migrations.AddConstraint(
            model_name='possibleactionstariff',
            constraint=models.UniqueConstraint(fields=('action', 'tariff'), name='double_actions'),
        ),
    ]
